package:
  name: jenkins
  version: "2.383"
  epoch: 0
  description:
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation:
      license: MIT
  dependencies:
    runtime:
      - ttf-dejavu
environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - coreutils
      - bash
      - openssh-client
      - tini
      - openjdk-17
      - maven
      - tzdata
      - glibc-locale-en
      - git
      - patch
      - ttf-dejavu
pipeline:
  - uses: fetch
    with:
      uri: https://github.com/jenkinsci/jenkins/archive/refs/tags/jenkins-${{package.version}}.tar.gz
      expected-sha256: 108a3d9e868299699faa06517e8a51a04dd66a1866604107924e53c6ff49b8b3
  - uses: patch
    with:
      patches: ignoreArchiveNotReadableTest.patch
  - runs: |
      export JAVA_HOME=/usr/lib/jvm/openjdk
      export LANG=en_US.UTF-8

      export MAVEN_OPTS="-DforkCount=2"
      mvn install

      mkdir -p ${{targets.destdir}}/usr/share/java/jenkins
      mv war/target/jenkins.war ${{targets.destdir}}/usr/share/java/jenkins/
