package:
  name: libarchive
  version: 3.6.2
  epoch: 0
  description: "multi-format archive and compression library"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: BSD-2-Clause
environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - bzip2-dev
      - lz4-dev
      - zstd-dev
      - zlib-dev
      - xz-dev
      - acl-dev
      - attr-dev
      - openssl-dev
      - expat-dev
secfixes:
  3.6.1-r2:
    - CVE-2022-36227
pipeline:
  - uses: fetch
    with:
      uri: http://libarchive.org/downloads/libarchive-${{package.version}}.tar.xz
      expected-sha256: 9e2c1b80d5fbe59b61308fdfab6c79b5021d7ff4ff2489fb12daf0a96a83551d
  - uses: patch
    with:
      patches: 0003-libarchive-Do-not-include-sys-mount.h-when-linux-fs..patch
  - uses: patch
    with:
      patches: CVE-2022-36227.patch
  - uses: autoconf/configure
    with:
      opts: --without-xml2
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
subpackages:
  - name: "libarchive-doc"
    description: "libarchive documentation"
    pipeline:
      - uses: split/manpages
      - uses: split/infodir
  - name: "libarchive-dev"
    description: "libarchive development headers"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libarchive
  - name: "libarchive-tools"
    description: "bsdtar and bsdcpio programs from libarchive"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/bsd* "${{targets.subpkgdir}}"/usr/bin/
