name: Wolfictl Update

on:
  push:
    branches: ['main'] # todo switch this to CRON

permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    name: Wolfictl Update
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: wolfi-dev/wolfictl/.github/actions@main
    - run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
    - run: wolfictl update https://github.com/${{github.repository}} --data-mapper-url https://raw.githubusercontent.com/rawlingsj/wup-mapper/0a435fb7855afd64b7c7327faef49008e8f62592/Test.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}