name: Wolfictl Lint

on:
  pull_request:
    branches: ['main']
jobs:
  lint:
    name: Wolfictl Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    - uses: wolfi-dev/wolfictl/.github/actions@main
    - run: wolfictl lint